In [1]:
import numpy as np

Declaring a matrix

In [4]:
m=np.array([[1,2],[3,4]])
print(m)

[[1 2]
 [3 4]]


In [5]:
type(m)   #return the numpy datatype 

numpy.ndarray

In [7]:
m.shape    #return the dimension of the matrix

(2, 2)

Declaring a scalar

In [9]:
s=5  #we can directly assign scalar like this 
s

5

In [10]:
type(s)

int

In [16]:
s_array=np.array(5)  #we can also declare scalar as a numpy array
s 


5

In [21]:
type(s_array)

numpy.ndarray

In [18]:
s_array.shape

()

Declaring a vector

In [23]:
v1=np.array([5,6,7,8])   #by default it is a row vector
v1


array([5, 6, 7, 8])

In [24]:
type(v1)

numpy.ndarray

In [25]:
v1.shape

(4,)

Creating a column vector


In [29]:
v1.reshape(4,1)


array([[5],
       [6],
       [7],
       [8]])

Creating Tensors

Rank 0 tensors ->scalars
Rank 1 tensors -> vectors
Rank 2 tensors -> matrix
Rank 3 tensors  are the collections of matrices _>k x m x n

In [30]:
m1=np.array([[1,2,3],[4,5,6]])

In [31]:
m2=np.array([[7,8,9],[10,11,12]])

In [32]:
t=np.array([m1,m2])
t

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [33]:
t.shape

(2, 2, 3)

In [36]:
t2=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
t2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [37]:
t3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [38]:
t3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [39]:
t3.shape

(2, 2, 2)

Adding  and subtracting 2 matrices

In [40]:
m1=np.array([[1,2,3],[4,5,6]])
m2=np.array([[7,8,9],[10,11,12]])

In [41]:
m1+m2


array([[ 8, 10, 12],
       [14, 16, 18]])

In [43]:
m2-m1

array([[6, 6, 6],
       [6, 6, 6]])

Adding  and subtracting 2 vectors

In [44]:
m1=np.array([1,2,3,4,5])
m2=np.array([100,50,75,25,10])

In [45]:
m1+m2

array([101,  52,  78,  29,  15])

In [46]:
m1-m2

array([-99, -48, -72, -21,  -5])

inorder to add or substract two matrices or vectors they have to be of same dimension or size.
but in python there is an exception with scalars.

In [48]:
m1=np.array([[1,2,3],[4,5,6]])
m1+1    #here the scalar 1 is added with all elements irrespective of different dimensions.

array([[2, 3, 4],
       [5, 6, 7]])

In [49]:
v1=np.array([1,2,3,4,5])
v1+1

array([2, 3, 4, 5, 6])

In [50]:
v1+np.array([1])

array([2, 3, 4, 5, 6])

In [51]:
m1+np.array([2])

array([[3, 4, 5],
       [6, 7, 8]])

Transposing matrices

In [52]:
m1=np.array([[1,2,3],[4,5,6]])
print(m1)
print(m1.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


Transposing vectors

In [54]:
v1=np.array([1,2,3,4,5])
print(v1.T)   #in python they are not actually transposed...

[1 2 3 4 5]


In [70]:
v1.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

Dot product of 2 vectors

In [75]:
v1=np.array([1,2,3,4,5])
v2=np.array([6,7,8,9,10])
np.dot(v1,v2)

np.int64(130)

dot product of 2 scalar

In [76]:
np.dot(5,6)

np.int64(30)

dot product of vector and scalar

In [78]:
v1=np.array([1,2,3,4,5])
np.dot(v1,5)

array([ 5, 10, 15, 20, 25])

In [79]:
v1*5

array([ 5, 10, 15, 20, 25])

Dot product of matrices

In [80]:
#scalar * matrix
m1=np.array([[1,2,3],[4,5,6]])
m1*5  #m1 matrix is scaled by 5 units


array([[ 5, 10, 15],
       [20, 25, 30]])

In [85]:
matrix1=np.array([[1,2,3],[4,5,6]])
matrix2=np.array([[7,8,9],[10,11,12],[13,14,15]])
np.dot(matrix1,matrix2)

array([[ 66,  72,  78],
       [156, 171, 186]])

mean


In [87]:
m1=np.array([[1,2,3],[4,5,6]])
print(np.mean(m1))     #it will return mean of m1


3.5


In [88]:
np.mean(m1,axis=1)  #it will give you row mean

array([2., 5.])

In [89]:
np.mean(m1,axis=0)  #it will give column mean

array([2.5, 3.5, 4.5])

In [91]:
np.mean(m1,dtype=np.int64)

np.int64(3)

ADDITIONAL POINTS

In [95]:
#to find the sum of elements in an array
m1=np.array([[1,2,3],[4,5,6]])
print(np.sum(m1))

#to find the sum of row elements in an array
print(np.sum(m1,axis=1))

#to find the sum of column elements in an array

print(np.sum(m1,axis=0))

21
[ 6 15]
[5 7 9]


In [119]:
#To create a matrix of order 2 x 2 with full zeros
A=np.zeros((2,2))
print("A",A)
#To create a matrix of order 2 x 2 with full ones
B=np.ones((2,2))
print("B",B)
#To create a 2 x 2 identity matrix
C=np.eye(2)
print("C",C)
#To create a matrix of order 2 x 3 with full 7
D=np.full((2,3),7)
print("D",D)
#To create a matrix of order 3 x 3 with full 10
E=np.full((3,3),10)
print("E",E)
#To create a vector of elements from 0-5
F=np.arange(6)
print("F",F)
#To create a vector of elements from 0-5 and reshaped it to matrix
G=np.arange(6).reshape(2,3)
print("G:",G)
#To create a matrix with random integers
H=np.random.randint(0,20,(3,3))
print("H:",H)

#to find standard deviation of H
print("Standard deviation of H:", np.std(H))
#To find Sqrt of a number
print(np.sqrt(25))


A [[0. 0.]
 [0. 0.]]
B [[1. 1.]
 [1. 1.]]
C [[1. 0.]
 [0. 1.]]
D [[7 7 7]
 [7 7 7]]
E [[10 10 10]
 [10 10 10]
 [10 10 10]]
F [0 1 2 3 4 5]
G: [[0 1 2]
 [3 4 5]]
H: [[17  4  5]
 [ 7 19  3]
 [17  2 16]]
Standard deviation of H: 6.649979114420001
5.0
